
export const ANDROID_EMULATOR_LOCALHOST = '10.0.2.2';
export const GENYMOTION_EMULATOR_LOCALHOST = '10.0.3.2';

export const API_BASE_HTTP_URL = `http://${GENYMOTION_EMULATOR_LOCALHOST}:10000/v1/`;

export const GRAPHQL_BASE_URL = `ws://${GENYMOTION_EMULATOR_LOCALHOST}:9003`;
export const GRAPHQL_URL = `${GRAPHQL_BASE_URL}/graphql`;

export const GRAPHQL_SUBSCRIPTIONS_URL = `ws://${GENYMOTION_EMULATOR_LOCALHOST}:9001`;
